name: smartstruct_example
description: example
version: 1.0.1
# homepage: https://www.example.com
environment:
  sdk: ">=2.12.0 <3.0.0"

publish_to: none
dependencies:
  freezed_annotation: ^2.1.0
  injectable: ^1.5.3
  smartstruct: ^1.3.0
dev_dependencies:
  build_runner: ^2.1.7
  freezed: ^2.1.0+1
  # Override to use latest change from GitHub
  # See https://github.com/Milad-Akarie/injectable/issues/315#issuecomment-1304700483
  injectable_generator:
    git:
      url: https://github.com/amondnet/injectable.git
      path: injectable_generator
  # smartstruct_generator: ^1.3.0
  smartstruct_generator:
   path: ../generator
dependency_overrides:
  smartstruct:
    path: ../smartstruct
